<a href="https://colab.research.google.com/github/StevenBryceLee/Programming_Challenges/blob/master/Josephus_Permutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://edabit.com/challenge/4AjWvJdZpFEMbGALd


A group of n prisoners stand in a circle awaiting execution. Starting from an arbitrary position(0), the executioner kills every kth person until one person remains standing, who is then granted freedom (see examples).

Create a function that takes 2 arguments — the number of people to be executed n, and the step size k, and returns the original position (index) of the person who survives.

In [41]:
import warnings
warnings.filterwarnings("ignore")

In [34]:
prisoners = np.arange(9)
executed = np.arange(1,len(prisoners),2)
executed

array([1, 3, 5, 7])

In [36]:
executed[-1] + 2 - prisoners[-1]

1

In [35]:
prisoners = np.delete(prisoners,executed)
prisoners

array([0, 2, 4, 6, 8])

In [ ]:
executed[-1] + step - prisoners[-1]

In [44]:
import numpy as np
def who_goes_free(n,step):
  prisoners = np.arange(n)
  print(prisoners)
  index = step
  while(len(prisoners) != 1):
    #Get mask of all steps in the prisoners
    executed = np.arange(index-1,len(prisoners),step)
    #Reset the index location to the correct point for next round
    index = executed[-1] + step - prisoners[-1]
    #Execute the prisoners
    prisoners = np.delete(prisoners,executed)
    print(prisoners)
  return prisoners[0]
who_goes_free(9,2)

[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]
[2 6]
[2]


2